name: Build and deploy ASP app to Azure Web App - ApplicationChat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="${{ github.workspace }}/published"

      - name: List files in the published directory
        run: ls -R ./published  # Debugging step to verify files are in the correct folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: './published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: List files in the downloaded artifact (debugging step)
        run: ls -R ./ASP-app  # Verify that the artifact was correctly downloaded

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F2C0EBF976AB40E4A5D2DC7B24BF35F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F3CA0D6DA844C92B6E44E4A5E49F73B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C67C5F516C94AB28506AAB68AC9045D }}
          auth-type: "SERVICE_PRINCIPAL"
          enable-AzPSSession: false
          environment: azurecloud

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ApplicationChat'
          slot-name: 'Production'
          package: '${{ github.workspace }}/published/**'  # Use absolute path to ensure correctness
